# Generated by Django 5.2.10 on 2026-01-19 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactstatuschoice_alter_contact_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactstatuschoice',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='contactstatuschoice',
            name='code',
        ),
        migrations.RemoveField(
            model_name='contactstatuschoice',
            name='label',
        ),
        migrations.AddField(
            model_name='contactstatuschoice',
            name='name',
            field=models.CharField(default='New', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contactstatuschoice'),
            preserve_default=False,
        ),
    ]
